[package]
name = "upm"
version = "0.1.0"
authors = ["Brandon Moore <moore.3071@osu.edu>"]
build = "build.rs"

[dependencies]
clap = "2.26.0"
toml = "0.4.5"
failure = "0.1.1"
[build-dependencies]
toml = "0.4.5"
